// Generated by Dogma Dart. DO NOT MODIFY!

library qe_model.src.models.generic_dimension_properties;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:dogma_convert/serialize.dart';
import 'nx_info.dart';
import 'nx_library_dimension_def.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

class GenericDimensionProperties {
  /// Identifier and type of the dimension. This parameter is mandatory.
  @Serialize.field('qInfo', optional: true)
  NxInfo qInfo;

  /// Definition of the dimension. This parameter is mandatory.
  @Serialize.field('qDim')
  NxLibraryDimensionDef qDim;
}
