// Generated by Dogma Dart. DO NOT MODIFY!

library qe_model.src.unmodifiable_model_views.unmodifiable_nx_info_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:qe_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [NxInfo].
class UnmodifiableNxInfoView implements NxInfo {
  final NxInfo _model;

  UnmodifiableNxInfoView(this._model);

  @override
  String get qId => _model.qId;
  set qId(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxInfo');
  }

  @override
  String get qType => _model.qType;
  set qType(String value) {
    throw new UnsupportedError('Cannot modify an unmodifiable NxInfo');
  }
}
