// Generated by Dogma Dart. DO NOT MODIFY!

library qe_model.src.unmodifiable_model_views.unmodifiable_generic_dimension_properties_view;

//---------------------------------------------------------------------
// Imports
//---------------------------------------------------------------------

import 'package:qe_model/models.dart';

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

/// An unmodifiable view over an instance of [GenericDimensionProperties].
class UnmodifiableGenericDimensionPropertiesView
    implements GenericDimensionProperties {
  final GenericDimensionProperties _model;

  UnmodifiableGenericDimensionPropertiesView(this._model);

  @override
  NxInfo get qInfo => _model.qInfo;
  set qInfo(NxInfo value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable GenericDimensionProperties');
  }

  @override
  NxLibraryDimensionDef get qDim => _model.qDim;
  set qDim(NxLibraryDimensionDef value) {
    throw new UnsupportedError(
        'Cannot modify an unmodifiable GenericDimensionProperties');
  }
}
